interface IThemes {
  light: string,
  lightColor: string,
  dark: string,
  darkColor: string,
  primary: string,
  darkTheme: string,
  lightTheme: string,
  blue: string,
  indigo: string,
  purple: string,
  pink: string,
  red: string,
  orange: string,
  yellow: string,
  green: string,
  teal: string,
  cyan: string,
  white: string,
  gray: string,
  grayDark: string,
  secondary: string,
  success: string
  info: string,
  warning: string,
  danger: string,
}

export const themes: IThemes = {
  light: "light",
  lightColor: "#E5E5E5",
  dark: "dark",
  darkColor: "#093545",
  primary: "primary",
  darkTheme: "https://cdn.jsdelivr.net/npm/@forevolve/bootstrap-dark@1.0.0/dist/css/bootstrap-dark.min.css",
  lightTheme: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css",
  blue: "blue",
  indigo: "indigo",
  purple: "purple",
  pink: "pink",
  red: "red",
  orange: "orange",
  yellow: "yellow",
  green: "green",
  teal: "teal",
  cyan: "cyan",
  white: "white",
  gray: "gray",
  grayDark: "gray-dark",
  secondary: "secondary",
  success: "success",
  info: "info",
  warning: "warning",
  danger: "danger",
}
